### PR TITLE
Introduce RealAudioDetector for #12

### LINKED ISSUE #12: Detect Real Audio sound format
Real Audio sound format

* https://en.wikipedia.org/wiki/RealAudio

Magic bytes:

* https://www.garykessler.net/library/file_sigs.html
* https://tool.lu/magicbytes/
* https://github.com/brynet/file/blob/master/magic

```
2E 52 4D 46 00 00 00 12 00
```
or maybe offset 0
```
# Real Audio (Magic .ra\0375)
0	belong		0x2e7261fd	RealAudio sound file
```

### PR DESCRIPTION
**Pull request by hyperized**
My first attempt to fix https://github.com/selective-php/audio-type/issues/12.
The only issue is I can't seem to find a file to test with. I can't just grab a random online file due to copyright constraints, is it possible for you to provide one?

### CODE REVIEW

**Comment by odan** [comment]
Hi! You should not add a full (big) test file.
We just need the first hundreds bytes (or even less) of a test file.

**Comment by hyperized** [comment]
@odan I completely understand, however I literally have no .rm files around and I seem unable to find any online as well. If you have a sample you can share, I would appreciate it.

**Comment by odan** [comment]
I guess there are no files anymore, because RealAudio was mainly used as a streaming audio format. It's also a quite old format. If you want, just add a pseudo file with a valid header (the magic bytes) as test file.

**Comment by hyperized** [comment]
@odan maybe it's a sign this code is going to be dead in the water to begin with. I'm OK with closing the PR and moving on 👯‍♂

**Comment by odan** [comment]
I agree. Thank you for your time and PR.

**Pull request closed without merging**
